// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
var CACHE_NAME  = "cinnamoroll-world-cache-v1";
var urlsToCache = [
  "/styles/main.css",
  "/scripts/main.js",
  "/index.html",
  "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css",
  "/images/cinnamon1.jpg"
];
self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(
        function(cache){
          return cache.addAll(urlsToCache);
        })
  );
});
self.addEventListener('fetch', function(event) {
  if (isImage(event.request.url)) {
    event.respondWith(
      caches.match(event.request).then(function (response) {
        return response || fetch(event.request);
      })
    );
  }
  else {
    event.respondWith(
      fetch(event.request).catch(function() {
        return caches.match(event.request);
      })
    );
  }
});

function isImage (url) {
  return Boolean(url.match(/(\.png)|(\.jpg)$/));
}
